import './globals.css'
import { Inter } from 'next/font/google'
import { ProviderRedux } from './ProviderRedux';
import { ProviderChakra } from './ProviderChakra';


const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'NextJS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={inter.className} suppressHydrationWarning={true}>
        <ProviderRedux>
          <ProviderChakra>
            {children}
          </ProviderChakra>
        </ProviderRedux>
      </body>
    </html>
  )
}
